# Generated by Django 3.0.6 on 2022-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policy_id', models.IntegerField()),
                ('Date_of_Purchase', models.DateField()),
                ('Customer_id', models.IntegerField()),
                ('Fuel', models.CharField(max_length=20)),
                ('VEHICLE_SEGMENT', models.CharField(max_length=10)),
                ('Premium', models.IntegerField()),
                ('bodily_injury_liability', models.IntegerField()),
                ('personal_injury_protection', models.IntegerField()),
                ('property_damage_liability', models.IntegerField()),
                ('collision', models.IntegerField()),
                ('comprehensive', models.IntegerField()),
                ('Customer_Gender', models.CharField(max_length=20)),
                ('Customer_Income_group', models.CharField(max_length=20)),
                ('Customer_Region', models.CharField(max_length=20)),
                ('Customer_Marital_status', models.IntegerField()),
            ],
        ),
    ]
