# Generated by Django 3.0.6 on 2022-02-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Fuel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
