# Generated by Django 3.0.6 on 2022-02-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220227_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date_of_Purchase',
            field=models.DateField(),
        ),
    ]
