# Generated by Django 3.0.6 on 2022-02-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220227_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer details'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_of_Purchase',
            field=models.DateField(editable=False),
        ),
    ]
