# Generated by Django 3.0.6 on 2022-02-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220228_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date_of_Purchase',
            field=models.DateField(),
        ),
    ]
